// Code automatically generated by "Generate_Cone_Mapping_Model" script by Jolyon Troscianko

//Model fits:
//swR2 0.999740614010378
//lwR2 0.999813466356591
//rodR2 0.999391618977155
// Modelled based on Natural Spectra 400-700 database, containing 3139 spectra.
// Generated: 2015/4/20   17:24:55
import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;
public class D7000_CoastalOpt_105mm_Pollack_D65 implements PlugInFilter {
ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {
float[] vR;
float[] vG;
float[] vB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;
float[] sw = new float[dimension];
float[] lw = new float[dimension];
float[] rod = new float[dimension];
vR = (float[]) stack.getPixels(1);
vG = (float[]) stack.getPixels(2);
vB = (float[]) stack.getPixels(3);
for (int i=0;i<dimension;i++) {
sw[i] = (float) ( 124.985201500587 + vR[i] * 0.00405378435656159 + vG[i] * -0.112707890268381 + vB[i] * 1.07779756379908 + vR[i]*vG[i] * -1.49464923292134e-08 + vR[i]*vB[i] * 1.96933527069933e-07 + vG[i]*vB[i] * 2.11417952666763e-07);
lw[i] = (float) ( -105.173031170762 + vR[i] * -0.154920241825897 + vG[i] * 0.900026699044044 + vB[i] * 0.262551645218815 + vR[i]*vG[i] * -3.26715645064168e-07 + vR[i]*vB[i] * 6.63036411002657e-07 + vG[i]*vB[i] * -3.91361558366775e-07);
rod[i] = (float) ( -180.402987243798 + vR[i] * -0.149253887869649 + vG[i] * 0.583920645024494 + vB[i] * 0.583111550571043 + vR[i]*vG[i] * -3.93455003255166e-07 + vR[i]*vB[i] * 8.98601987879807e-07 + vG[i]*vB[i] * -6.67778861562884e-07);
}
ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("sw", sw);
outStack.addSlice("lw", lw);
outStack.addSlice("rod", rod);
new ImagePlus("Output", outStack).show();
}
}
