// Code automatically generated by "Generate_Cone_Mapping_Model" script by Jolyon Troscianko

//Model fits:
//swR2 0.996320730010926
//mwR2 0.999236301107293
//lwR2 0.996446489914381
//dblR2 0.999533482614794
// Modelled based on Natural Spectra 400-700 database, containing 3139 spectra.
// Generated: 2015/4/20   17:28:33
import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;
public class D7000_CoastalOpt_105mm_Peafowl_D65 implements PlugInFilter {
ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {
float[] vR;
float[] vG;
float[] vB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;
float[] sw = new float[dimension];
float[] mw = new float[dimension];
float[] lw = new float[dimension];
float[] dbl = new float[dimension];
vR = (float[]) stack.getPixels(1);
vG = (float[]) stack.getPixels(2);
vB = (float[]) stack.getPixels(3);
for (int i=0;i<dimension;i++) {
sw[i] = (float) ( -532.494001903421 + vR[i] * -0.136490939706609 + vG[i] * 0.468249583377058 + vB[i] * 0.731715199328986 + vR[i]*vG[i] * -7.79199300260191e-07 + vR[i]*vB[i] * 6.41229052848078e-07 + vG[i]*vB[i] * -4.40825238578686e-07);
mw[i] = (float) ( 382.959276106162 + vR[i] * -0.300696557268496 + vG[i] * 1.64326966746643 + vB[i] * -0.362968249875079 + vR[i]*vG[i] * 3.58059919849485e-07 + vR[i]*vB[i] * 3.75729889693545e-08 + vG[i]*vB[i] * -3.16602336265533e-07);
lw[i] = (float) ( -547.843882339263 + vR[i] * 0.698577840780668 + vG[i] * 0.661798751905345 + vB[i] * -0.382714585364367 + vR[i]*vG[i] * -2.79021613294704e-06 + vR[i]*vB[i] * 1.54388604793444e-06 + vG[i]*vB[i] * 1.82736717426906e-06);
dbl[i] = (float) ( -99.1794622801112 + vR[i] * 0.0416339647885522 + vG[i] * 1.20769876383792 + vB[i] * -0.262583941033759 + vR[i]*vG[i] * -6.82908258221748e-07 + vR[i]*vB[i] * 2.08014955366867e-07 + vG[i]*vB[i] * 7.18714686850208e-07);
}
ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("sw", sw);
outStack.addSlice("mw", mw);
outStack.addSlice("lw", lw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();
}
}
